version: '3.3'

services:
  enigmabbs:
    image: enigmabbs/enigma-bbs:latest
    container_name: ENiGMABBS
    ports:
      - "8888:8888"
    volumes:
      - "./config:/enigma-bbs/config"
      - "./db:/enigma-bbs/db"
      - "./logs:/enigma-bbs/logs"
      - "./filebase:/enigma-bbs/filebase"
      - "./art:/enigma-bbs/art"
      - "./mods:/enigma-bbs/mods"
      - "./mail:/mail"
